mk_auto/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import TemplateView
from mk_auto import views
from feedbacks.views import FeedbackView
from appointments.views import AppointmentView

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mk_auto.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.IndexView.as_view(), name="index"),
    url(r'^contact/$', TemplateView.as_view(template_name='contact.html'), name='contact'),
    url(r'^services/', include('services.urls', namespace="services")),
    url(r'^feedback/$', FeedbackView.as_view(), name='feedback'),
    url(r'^appointment/$', AppointmentView.as_view(), name='appointment'), 
    #url(r'^$', SlideListView.as_view(), name="index"),
    url(r'^slides/', include('slides.urls', namespace="slides")),   
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

slides/urls.py
from django.conf.urls import patterns, include, url
from slides import views

urlpatterns = patterns('',
    url(r'^$', views.SlideListView.as_view(), name='list_view'),
)

appointments/models.py
# -*- coding: utf-8 -*- 
from django.db import models
import datetime
from services.models import Service


class Appointment(models.Model):
    name = models.CharField( max_length=225, verbose_name=u'Ваше имя')
    surname = models.CharField( max_length=225, verbose_name=u'Ваша Фамилия')
    phone = models.CharField(max_length=15, verbose_name=u'Телефон')
    brand_auto = models.CharField( max_length=225, verbose_name=u'марка автомобиля')
    model_auto = models.CharField( max_length=225, verbose_name=u'модель авто')
    VIN = models.CharField( max_length=225)
    birth_of_auto = models.IntegerField(verbose_name=u'дата выпуска автомобиля')
    service = models.ManyToManyField(Service, verbose_name=u'вид сервиса')
    message = models.TextField(verbose_name=u'причина обращения')
    from_email = models.EmailField(default='example@mail.com')
    create_date = models.DateTimeField(auto_now_add=True)
    date = models.DateTimeField(default = datetime.datetime.now, verbose_name=u'желаемая дата ремонта')

    def __unicode__(self):
		return self.brand_auto

feedbacks/models.py
# -*- coding: utf-8 -*- 
from django.db import models
import datetime
from services.models import Service


class Feedback(models.Model):
    name = models.CharField( max_length=225, verbose_name=u'Ваше имя')
    subject = models.CharField(max_length=255, verbose_name=u'тема')
    message = models.TextField(verbose_name=u'сообщение')
    from_email = models.EmailField()
    create_date = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
		return self.subject

appointments/forms.py
# -*- coding: utf-8 -*- 
from django import forms
from appointments.models import Appointment



class AppointmentForm(forms.ModelForm):
    class Meta:
        model = Appointment
        fields = '__all__'

feedbacks/forms.py
# -*- coding: utf-8 -*- 
from django import forms
from feedbacks.models import Feedback



class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = '__all__'

appointments/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from django.contrib import messages
from django.views.generic.edit import CreateView
from django.core.urlresolvers import reverse_lazy, reverse
from django.core.mail import mail_admins
from appointments.forms import AppointmentForm
from appointments.models import Appointment

class AppointmentView(CreateView):
    model = Appointment
    template_name = 'appointment.html'
    form_class = AppointmentForm
    context_object_name = 'form'
    success_url = reverse_lazy('appointment')
    
    def get_context_data(self, **kwargs):
        context = super(AppointmentView, self).get_context_data(**kwargs)
        context['title'] = "Запись на ремонт"
        return context 

    def form_valid(self, form):
        appointment = form.save()
        messages.success(self.request, u"Спасибо за Ваше сообщение! Наш менеджер перезвонит Вам!")
        mail_admins(appointment.name, appointment.phone, appointment.message)
        return super(AppointmentView, self).form_valid(form)

feedbacks/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from django.contrib import messages
from django.views.generic.edit import CreateView
from django.core.urlresolvers import reverse_lazy, reverse
from django.core.mail import mail_admins
from feedbacks.forms import FeedbackForm
from feedbacks.models import Feedback

class FeedbackView(CreateView):
    model = Feedback
    template_name = 'feedback.html'
    form_class = FeedbackForm
    context_object_name = 'form'
    success_url = reverse_lazy('feedback')
    #success_message = u"Thank you for your feedback! We will keep in touch with you very soon!"
    
    def get_context_data(self, **kwargs):
        context = super(FeedbackView, self).get_context_data(**kwargs)
        context['title'] = "Обратная связь"
        return context 

    def form_valid(self, form):
        feedback = form.save()
        messages.success(self.request, u"Спасибо за Ваше сообщение! Наш менеджер перезвонит Вам!")
        mail_admins(feedback.subject, feedback.message)
        return super(FeedbackView, self).form_valid(form)

templates/appointment.html
{% extends "base.html" %}


{% load staticfiles %}


{% block title %}home_mk_auto{% endblock title %}


{% block nav_brand_index %}active{% endblock %}


{% block content %}


		<div class="panel panel-default">
  		<div><h2>{{ title }}</h2>
      {% if messages %}
        <div class="messages">
          {% for message in messages %}
            <p class="bg-info">{{ message }}</p>
          {% endfor %}
        </div>
        {% endif %}
      </div>   
<form method="post">
          {% csrf_token %}   
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="@getbootstrap">Записаться</button>
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" >
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="exampleModalLabel">Заполните форму ниже</h4>
      </div>
      <div class="modal-body">
          <div class="form-group">
            <label for="recipient-name" class="control-label">{{ form.as_p }}</label>
          </div>          
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>       
         <button type="submit" class="btn btn-primary">Отправить</button>
 </div>
    </div>
  </div>
</div>         
</form>
</div>
{% endblock content %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en" class="no-js">
	<head>
	    <meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> 
		<meta name="viewport" content="width=device-width, initial-scale=1.0"> 
		<title>{% block title %}{% endblock title %}</title>
		<meta name="keywords" content="fixed header, animatied header, javascript, wed design, template, on scroll" />
		<meta name="author" content="Moroz" />
    <link href="{% static 'css/pulse.css' %}" rel="stylesheet" />   
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" />
    <link type="text/css" href="{% static 'css/m_auto_navbar.css' %}" rel="stylesheet" />
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
	  <script type="text/javascript">
var _gaq = _gaq || [];
_gaq.push(['_setAccount', 'UA-7243260-2']);
_gaq.push(['_trackPageview']);
(function() {
var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
})();
    </script>
	</head>
	<body>
		<div class="container">
			<div class="main-header">
				<div class="cbp-af-inner">
					<h4>M_Auto</h4>          
					<nav class="nav-main">      
						<a href="{% url 'index' %}"><i class="fa fa-home fa-fw"></i> m_auto</a></li>                        
						<a href="{% url 'services:list_view' %}"><i class="fa fa-wrench"></i> услуги</a> 
            <a href="{% url 'slides:list_view' %}"><i class="fa fa-group fa-fw"></i> о нас</a></li>        
            <a href="{% url 'contact' %}"><i class="fa fa-map-marker fa-fw"></i> контакты</a>
            <a class="feedback" href="{% url 'feedback' %}"><i class="fa fa-phone-square"></i> обратная связь</a>
					</nav>
				</div>
			</div>
    </div>
{% block content %}{% endblock content %} 
    <script src="{% static 'js/jquery-1.11.3.min.js' %}"></script>
    <script src="{% static 'js/m_auto.js' %}"></script>	
    <script src="{% static 'js/m_auto_navigation.min.js' %}"></script>    	
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/background.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
	</body>
</html>

templates/contact.html
{% extends "base.html" %}


{% load staticfiles %}


{% block title %}home_mk_auto{% endblock title %}


{% block nav_brand_index %}active{% endblock %}


{% block content %}


{% endblock content %}

templates/feedback.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Bootstrap 101 Template</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="{% static 'css/foundations-icons.css' %}" />
    <link rel="stylesheet" href="{% static 'css/typicons.css' %}" />
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" />

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <div>
		<div class="panel panel-default">
  		<div><h2>{{ title }}</h2>
      {% if messages %}
        <div class="messages">
          {% for message in messages %}
            <h4>{{ message }}</h4>
          {% endfor %}
        </div>
        {% endif %}
      </div>   
<form method="post">
          {% csrf_token %}   
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="@getbootstrap">k_moroz@hotmail.com</button>
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" >
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="exampleModalLabel">Напишите Ваше сообщение</h4>
      </div>
      <div class="modal-body">
          <div class="form-group">
            <label for="recipient-name" class="control-label">{{ form.as_p }}</label>
          </div>          
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
        
         <button type="submit" class="btn btn-primary">Отправить</button>
          </div>
    </div>
  </div>
</div>
         </form>
  </div>
</div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{% static 'js/jquery-1.11.3.min.js' %}"></script>	
	  <script src="{% static 'js/m_auto.js' %}"></script>   	
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  </body>
</html>

templates/index.html
{% extends "base.html" %}


{% load staticfiles %}


{% block title %}home_mk_auto{% endblock title %}


{% block nav_brand_index %}active{% endblock %}


{% block content %}

<div class="background-img-head-content" data-type="background" data-speed="7">
  <div class="background-color-head-content">
    <div class="head-content">
      <div class="container">
        <h2 id="h2-head-content"><img src="{% static 'images/1_Primary_logo_on_transparent_225x75.png'%}" alt="..."></h2>          
          <h6>autoservice</h6>            
         <p class="p-head-content"><a class="btn-about_us" href="#" role="button">о компании</a></p>
         <div class="pulse1"><p class="p-arrow-down"><i class="fa fa-arrow-circle-o-down fa-2x"></i></p></div>
      </div>
    </div>
  </div>
</div>

<div class="main-appointment">
      <div class="container">
           {% for onlines in online %}
        <h1 class="h1-appointment-content">{{ onlines.name }}</h1>
        <h2 class="h2">{{ onlines.title }}</i></h2>     
          <p class="p-text">{{ onlines.description }}</p>
{% endfor %}
          <p class="p-appointment-content"><a class="btn-appointment" href="{% url 'appointment' %}" role="button"><i class="fa fa-pencil"></i> Начать запись</a></p>
      </div>
    </div>
<div class="background-img-service-content" data-type="background" data-speed="7">
  <div class="background-color-service-content">
    <div class="service-content">
      <div class="row">
  {% for service in services %}
        <div class="col-xs-6 col-md-3">
          <a href="#" class="thumbnail">
            <img class="service-img" src="{{ service.photo.url }}">
          </a>
        </div>
{% endfor %}
      </div>
    </div>
  </div>
</div>
<div class="background-img-social-content">
    <div class="social-content">
      <img src="{% static 'images/soc_block.png' %}">
      <div class="social-item">
        <ul class="facebook">
          <a href="#"><i class="fa fa-facebook-official fa-4x"></i></a> 
          <a href="#"><i class="fa fa-vk fa-4x"></i></a>
        </ul>
    </div>
  </div>
</div>
   
{% endblock content %}